let menuadd = '/api/menuadd',
    menulist = '/api/menulist',
    menuinfo = '/api/menuinfo',
    menuedit = '/api/menuedit',
    menudelete = '/api/menudelete',
    roleadd = '/api/roleadd',
    rolelist = '/api/rolelist',
    roleinfo = '/api/roleinfo',
    roleedit = '/api/roleedit',
    roledelete = '/api/roledelete',
    useradd = '/api/useradd',
    usercount = '/api/usercount',
    userlist = '/api/userlist',
    userinfo = '/api/userinfo',
    useredit = '/api/useredit',
    userdelete = '/api/userdelete',
    cateadd = '/api/cateadd',
    catelist = '/api/catelist',
    cateslist = '/api/cateslist',
    cateinfo = '/api/cateinfo',
    cateedit = '/api/cateedit',
    catedelete = '/api/catedelete',
    specsadd = '/api/specsadd',
    specscount = '/api/specscount',
    specslist = '/api/specslist',
    specsinfo = '/api/specsinfo',
    specsedit = '/api/specsedit',
    specsdelete = '/api/specsdelete',
    goodsadd = '/api/goodsadd',
    goodscount = '/api/goodscount',
    goodslist = '/api/goodslist',
    goodsinfo = '/api/goodsinfo',
    goodsedit = '/api/goodsedit',
    goodsdelete = '/api/goodsdelete',
    memberlist = '/api/memberlist',
    memberinfo = '/api/memberinfo',
    memberedit = '/api/memberedit',
    banneradd = '/api/banneradd',
    bannerlist = '/api/bannerlist',
    bannerinfo = '/api/bannerinfo',
    banneredit = '/api/banneredit',
    bannerdelete = '/api/menulibannerdeletest',
    getcategoods = '/api/getcategoods',
    getseckill = '/api/getseckill',
    getcatetree = '/api/getcatetree',
    getindexgoods = '/api/getindexgoods',
    getgoodsinfo = '/api/getgoodsinfo'
    
export default {
    getcatetree,
    getseckill,
    getindexgoods,
    getgoodsinfo,
    getcategoods,
    menuadd,
    menulist,
    menuinfo,
    menuedit,
    menudelete,
    roleadd,
    rolelist,
    roleinfo,
    roleedit,
    roledelete,
    useradd,
    usercount,
    userlist,
    userinfo,
    useredit,
    userdelete,
    cateadd,
    catelist,
    cateslist,
    cateinfo,
    cateedit,
    catedelete,
    specsadd,
    specscount,
    specslist,
    specsinfo,
    specsedit,
    specsdelete,
    goodsadd,
    goodscount,
    goodslist,
    goodsinfo,
    goodsedit,
    goodsdelete,
    memberlist,
    memberinfo,
    memberedit,
    banneradd,
    bannerlist,
    bannerinfo,
    banneredit,
    bannerdelete,
}